### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by seven0813** [HouLeiHIT/HIT-dataset#4]
您好，非常感谢您和您的团队提供了这份免费的数据集。
在论文"An Inter-Shaft Bearing Fault Diagnosis Dataset from an Aero-Engine System"中，提到了“The data from 6 channels are sequenced to generate a two-dimensional time series array for machine learning training and testing." ，能否告知这句话的更具体信息，二维时序矩阵具体是如何构造的呢。
谢谢

**Comment by HouLeiHIT** [comment]
感谢您的关注
这里是一处笔误，应该是一维时间序列，感谢您发现了它，我们会联系编辑部修改

**Comment by seven0813** [comment]
感谢您的回复，请问能否告知贵团队是如何将六个通道的数据变成一个一维时序数据的呢？
期待您的解答

**Comment by HouLeiHIT** [comment]
> 感谢您的回复，请问能否告知贵团队是如何将六个通道的数据变成一个一维时序数据的呢？ 期待您的解答

原数据的长度是20480，为了适配TST模型，我们将其分割为2048长度的序列，并将六个通道的数据混合在一起随机排列，组成训练集合测试集。
