### ISSUE TITLE
Please provide the code to publish an article.

### ISSUE THREAD

**Issue by wchengming** [HouLeiHIT/HIT-dataset#5]
I have carefully studied your paper and conducted experiments using a part of the dataset. However, the results are not as expected. Could you please publish the code for the 'BENCHMARK STUDY OF MACHINE LEARNING' section, solely for learning purposes?

**Comment by HouLeiHIT** [comment]
The code for the models used in this paper is from other published papers, the purpose of this paper is only to publish the data set, and we have no plans to re-publish the code at present. The source of the code for CNN and RNNLSTM can be found in the references.
